server:
  port: 8080
  
spring:
  application:
    name: CRZuul

zuul:
  routes:
    simple:
      path: /simple/baidu
      url: http://www.baidu.com
    CRBook: /book/**
    CRUser: /user/**
    base:
      path: /**
      serviceId: CRIndex

# zuul连接超时配置      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
       